"""
Open Brain Setup Wizard - Interactive first-run configuration
"""

import copy
import os
import secrets
import yaml
from pathlib import Path
from typing import Any, Dict, Mapping

from ..providers.host_config import restrict_file_permissions
from ..runtime_config import configure_runtime_environment


_ENVIRONMENT_KEYS = (
    "OPENROUTER_API_KEY",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "MINIMAX_API_KEY",
    "CUSTOM_API_KEY",
    "OLLAMA_BASE_URL",
    "OPENBRAIN_API_KEY",
)
_SECRET_CONFIG_KEYS = {"password", "api_key", "token", "bot_token", "smtp_password"}


def _without_secrets(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: _without_secrets(item)
            for key, item in value.items()
            if key.lower() not in _SECRET_CONFIG_KEYS
        }
    if isinstance(value, list):
        return [_without_secrets(item) for item in value]
    return copy.deepcopy(value)


def _render_env_file(
    config: Mapping[str, Any],
    environment: Mapping[str, str],
) -> str:
    database = config.get("database", {})
    api = config.get("api", {})
    dashboard = config.get("dashboard", {})
    security = config.get("security", {})
    embedder = config.get("embedder", {})

    values: dict[str, Any] = {
        "DB_HOST": database.get("host", "localhost"),
        "DB_PORT": database.get("port", 5432),
        "DB_NAME": database.get("name", "openbrain"),
        "DB_USER": database.get("user", "postgres"),
        "DB_PASSWORD": database.get("password", ""),
        "DB_TIMEZONE": database.get("timezone", "auto"),
        "EMBEDDER_PROVIDER": embedder.get("provider", "ollama"),
        "EMBED_MODEL": embedder.get("model", ""),
        "API_PORT": api.get("port", 8000),
        "DASHBOARD_PORT": dashboard.get("port", 8501),
        "SECURITY_MODE": security.get("mode", "direct"),
    }
    if embedder.get("ollama_base_url"):
        values["OLLAMA_BASE_URL"] = embedder["ollama_base_url"]
    if embedder.get("custom_base_url"):
        values["CUSTOM_API_URL"] = embedder["custom_base_url"]

    notifications = config.get("analytics", {}).get("notifications", {})
    telegram = notifications.get("telegram", {})
    email = notifications.get("email", {})
    values.update(
        {
            "TELEGRAM_BOT_TOKEN": telegram.get("bot_token", ""),
            "TELEGRAM_CHAT_ID": telegram.get("chat_id", ""),
            "SMTP_HOST": email.get("smtp_host", ""),
            "SMTP_PORT": email.get("smtp_port", ""),
            "SMTP_USER": email.get("smtp_user", ""),
            "SMTP_PASSWORD": email.get("smtp_password", ""),
            "EMAIL_FROM": email.get("from_email", ""),
        }
    )
    for key in _ENVIRONMENT_KEYS:
        if environment.get(key):
            values[key] = environment[key]
    values.setdefault("OPENBRAIN_API_KEY", secrets.token_urlsafe(32))
    values.setdefault("OPENBRAIN_AUTH_REQUIRED", "true")
    values.setdefault("OPENBRAIN_URL", "http://127.0.0.1:8000")

    lines = ["# Open Brain environment generated by the setup wizard"]
    lines.extend(f"{key}={value}" for key, value in values.items() if value != "")
    return "\n".join(lines) + "\n"


def save_configuration(
    config: Mapping[str, Any],
    *,
    project_root: Path,
    environment: Mapping[str, str] | None = None,
) -> tuple[Path, Path]:
    """Write non-secret YAML configuration and a private environment file."""
    project_root = project_root.expanduser().resolve()
    config_path = project_root / "config" / "settings.yaml"
    env_path = project_root / ".env"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    config_path.write_text(
        yaml.safe_dump(_without_secrets(config), default_flow_style=False, sort_keys=False),
        encoding="utf-8",
    )
    env_path.write_text(
        _render_env_file(config, environment or os.environ),
        encoding="utf-8",
    )
    restrict_file_permissions(env_path)
    return config_path, env_path


def prompt_env(var_name: str, default: str = "", secret: bool = False) -> str:
    """Prompt for environment variable."""
    if secret:
        import getpass
        return getpass.getpass(f"{var_name}: ") or default
    return input(f"{var_name} [{default}]: ") or default


def run_setup() -> Dict[str, Any]:
    """Run interactive setup wizard."""
    print("""
╔═══════════════════════════════════════════════════════════════╗
║              Open Brain Setup Wizard v1.0                 ║
║                                                           ║
║  Your personal semantic memory system                     ║
╚═══════════════════════════════════════════════════════════════╝
    """)
    
    config = {}
    
    # ═══════════════════════════════════════════════════════
    # 1. DATABASE CONFIGURATION
    # ═══════════════════════════════════════════════════════
    print("\n📀 DATABASE CONFIGURATION")
    print("─" * 50)
    config['database'] = {
        'host': prompt_env("DB_HOST", "postgres"),
        'port': int(prompt_env("DB_PORT", "5432")),
        'name': prompt_env("DB_NAME", "openbrain"),
        'user': prompt_env("DB_USER", "postgres"),
        'password': prompt_env("DB_PASSWORD", "", secret=True) or secrets.token_urlsafe(24),
    }
    
    # ═══════════════════════════════════════════════════════
    # 2. EMBEDDING PROVIDER
    # ═══════════════════════════════════════════════════════
    print("\n🧠 EMBEDDING PROVIDER")
    print("─" * 50)
    print("Choose your embedding provider:")
    print("  1. OpenRouter  - Hosted embeddings (API key required)")
    print("  2. OpenAI      - GPT embeddings")
    print("  3. Ollama      - Local embeddings")
    print("  4. Custom      - Any OpenAI-compatible API")
    
    choice = input("\nChoice [1]: ") or "1"
    
    embedder_config = {}
    
    if choice == "1":  # OpenRouter
        embedder_config['provider'] = 'openrouter'
        embedder_config['model'] = prompt_env("EMBED_MODEL", "text-embedding-3-small")
        embedder_config['dimensions'] = 768
        api_key = prompt_env("OPENROUTER_API_KEY", "", secret=True)
        if api_key:
            os.environ['OPENROUTER_API_KEY'] = api_key
            
    elif choice == "2":  # OpenAI
        embedder_config['provider'] = 'openai'
        embedder_config['model'] = prompt_env("EMBED_MODEL", "text-embedding-3-small")
        embedder_config['dimensions'] = 1536
        api_key = prompt_env("OPENAI_API_KEY", "", secret=True)
        if api_key:
            os.environ['OPENAI_API_KEY'] = api_key
            
    elif choice == "3":  # Ollama
        embedder_config['provider'] = 'ollama'
        embedder_config['model'] = prompt_env("EMBED_MODEL", "nomic-embed-text")
        embedder_config['dimensions'] = 768
        embedder_config['ollama_base_url'] = prompt_env("OLLAMA_BASE_URL", "http://localhost:11434")
        
    elif choice == "4":  # Custom
        embedder_config['provider'] = 'custom'
        embedder_config['model'] = prompt_env("EMBED_MODEL", "text-embedding-ada-002")
        embedder_config['dimensions'] = 1536
        embedder_config['custom_base_url'] = prompt_env("CUSTOM_API_URL", "https://api.openai.com/v1")
        api_key = prompt_env("CUSTOM_API_KEY", "", secret=True)
        if api_key:
            os.environ['CUSTOM_API_KEY'] = api_key
    
    config['embedder'] = embedder_config
    
    # ═══════════════════════════════════════════════════════
    # 3. LLM PROVIDER (for MCP server)
    # ═══════════════════════════════════════════════════════
    print("\n🤖 LLM PROVIDER (for MCP)")
    print("─" * 50)
    print("Choose LLM for the MCP server:")
    print("  1. OpenRouter - Hosted models (API key required)")
    print("  2. OpenAI     - GPT-4, GPT-4o")
    print("  3. Anthropic  - Claude models")
    print("  4. Ollama     - Local models")
    print("  5. MiniMax    - Fast & cheap")
    
    llm_choice = input("\nChoice [1]: ") or "1"
    
    llm_config = {}
    
    if llm_choice == "1":
        llm_config['provider'] = 'openrouter'
        llm_config['model'] = prompt_env("LLM_MODEL", "openai/gpt-4o-mini")
        api_key = os.environ.get('OPENROUTER_API_KEY') or prompt_env("OPENROUTER_API_KEY", "", secret=True)
        if api_key:
            os.environ['OPENROUTER_API_KEY'] = api_key
            
    elif llm_choice == "2":
        llm_config['provider'] = 'openai'
        llm_config['model'] = prompt_env("LLM_MODEL", "gpt-4o-mini")
        api_key = prompt_env("OPENAI_API_KEY", "", secret=True)
        if api_key:
            os.environ['OPENAI_API_KEY'] = api_key
            
    elif llm_choice == "3":
        llm_config['provider'] = 'anthropic'
        llm_config['model'] = prompt_env("LLM_MODEL", "claude-3-haiku-20240307")
        api_key = prompt_env("ANTHROPIC_API_KEY", "", secret=True)
        if api_key:
            os.environ['ANTHROPIC_API_KEY'] = api_key
            
    elif llm_choice == "4":
        llm_config['provider'] = 'ollama'
        llm_config['model'] = prompt_env("LLM_MODEL", "llama3")
        llm_config['base_url'] = prompt_env("OLLAMA_BASE_URL", "http://localhost:11434")
        
    elif llm_choice == "5":
        llm_config['provider'] = 'minimax'
        llm_config['model'] = prompt_env("LLM_MODEL", "MiniMax-M2.1")
        api_key = prompt_env("MINIMAX_API_KEY", "", secret=True)
        if api_key:
            os.environ['MINIMAX_API_KEY'] = api_key
    
    config['llm'] = llm_config
    
    # ═══════════════════════════════════════════════════════
    # 4. API SERVER
    # ═══════════════════════════════════════════════════════
    print("\n🌐 API SERVER")
    print("─" * 50)
    config['api'] = {
        'host': '127.0.0.1',
        'port': int(prompt_env("API_PORT", "8000")),
        'cors_origins': ['http://localhost:8501', 'http://localhost:8000'],
    }
    
    config['mcp'] = {
        'transport': 'stdio',
    }
    
    config['dashboard'] = {
        'port': int(prompt_env("DASHBOARD_PORT", "8501")),
    }
    
    # ═══════════════════════════════════════════════════════
    # 5. SECURITY
    # ═══════════════════════════════════════════════════════
    print("\n🔒 SECURITY")
    print("─" * 50)
    config['security'] = {
        'mode': prompt_env("SECURITY_MODE", "direct"),
    }
    
    # ═══════════════════════════════════════════════════════
    # 6. NOTIFICATIONS (Optional)
    # ═══════════════════════════════════════════════════════
    print("\n📬 NOTIFICATIONS (Optional)")
    print("─" * 50)
    
    analytics = {'notifications': {}}
    
    if input("Enable Telegram? [y/N]: ").lower() == 'y':
        analytics['notifications']['telegram'] = {
            'enabled': True,
            'bot_token': prompt_env("TELEGRAM_BOT_TOKEN", ""),
            'chat_id': prompt_env("TELEGRAM_CHAT_ID", ""),
        }
    
    if input("Enable Email? [y/N]: ").lower() == 'y':
        analytics['notifications']['email'] = {
            'enabled': True,
            'smtp_host': prompt_env("SMTP_HOST", "smtp.gmail.com"),
            'smtp_port': int(prompt_env("SMTP_PORT", "587")),
            'smtp_user': prompt_env("SMTP_USER", ""),
            'smtp_password': prompt_env("SMTP_PASSWORD", "", secret=True),
            'from_email': prompt_env("EMAIL_FROM", ""),
        }
    
    config['analytics'] = analytics
    
    # Tags config
    config['tags'] = {
        'deny_list': ['password', 'secret', 'api_key', 'token', 'credential'],
        'default_tags': ['auto'],
    }
    
    # ═══════════════════════════════════════════════════════
    # SAVE CONFIGURATION
    # ═══════════════════════════════════════════════════════
    print("\n💾 SAVING CONFIGURATION")
    print("─" * 50)
    
    project_root = Path(__file__).resolve().parents[2]
    config_path, env_path = save_configuration(
        config,
        project_root=project_root,
        environment=os.environ,
    )
    configure_runtime_environment(project_root=project_root)
    print(f"✓ Configuration saved to: {config_path}")
    print(f"✓ Environment variables saved to: {env_path}")
    
    print("""
╔═══════════════════════════════════════════════════════════════╗
║                   SETUP COMPLETE!                         ║
║                                                           ║
║  Next steps:                                              ║
║  1. Review config/settings.yaml                         ║
║  2. docker compose up -d                                ║
║  3. Visit http://localhost:8501                        ║
╚═══════════════════════════════════════════════════════════════╝
    """)
    
    return config


if __name__ == "__main__":
    run_setup()
